# Generated by Django 5.1.2 on 2024-11-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='images',
            field=models.JSONField(blank=True, default='[]', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='main_image',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
